package com.skillbridge.skillbridge.utility;

import java.time.Year;

public class EmailBody {
    public static String getMessageBody(String name) {
        return "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title>Welcome to Job Alerts</title>\n"
                + "    <style>\n"
                + "        body {\n"
                + "            font-family: Arial, sans-serif;\n"
                + "            margin: 0;\n"
                + "            padding: 0;\n"
                + "            background-color: #f4f4f4;\n"
                + "        }\n"
                + "        .container {\n"
                + "            max-width: 600px;\n"
                + "            margin: 0 auto;\n"
                + "            padding: 20px;\n"
                + "            background-color: #ffffff;\n"
                + "            border-radius: 8px;\n"
                + "            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\n"
                + "        }\n"
                + "        .header {\n"
                + "            background-color: #4CAF50;\n"
                + "            color: #ffffff;\n"
                + "            padding: 10px;\n"
                + "            text-align: center;\n"
                + "            border-radius: 8px 8px 0 0;\n"
                + "        }\n"
                + "        .body {\n"
                + "            padding: 20px;\n"
                + "            color: #333333;\n"
                + "            text-align: center;\n"
                + "        }\n"
                + "        .highlight {\n"
                + "            font-size: 24px;\n"
                + "            font-weight: bold;\n"
                + "            color: #4CAF50;\n"
                + "            margin: 20px 0;\n"
                + "        }\n"
                + "        .footer {\n"
                + "            margin-top: 20px;\n"
                + "            font-size: 12px;\n"
                + "            color: #888888;\n"
                + "            text-align: center;\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "    <div class=\"container\">\n"
                + "        <div class=\"header\">\n"
                + "            <h1>Welcome to Job Alerts!</h1>\n"
                + "        </div>\n"
                + "        <div class=\"body\">\n"
                + "            <p>Hello <strong>" + name + "</strong>,</p>\n"
                + "            <p>Thank you for subscribing to our Job Alerts. You will be the first to know about new job opportunities in your area of interest.</p>\n"
                + "            <p class=\"highlight\">Stay tuned for the latest job updates!</p>\n"
                + "            <p>We’re excited to help you take the next step in your career!</p>\n"
                + "            <p>If you have any questions, feel free to reach out to us anytime.</p>\n"
                + "            <p>Thank you for being part of the SkillBridge community!</p>\n"
                + "        </div>\n"
                + "        <div class=\"footer\">\n"
                + "            <p>&copy;" + Year.now().getValue() + " SkillBridge. All rights reserved.</p>\n"
                + "        </div>\n"
                + "    </div>\n"
                + "</body>\n"
                + "</html>";
    }
}
